name: Build and deploy areweserveryet.org

on:
  push:
    branches:
    - main

env:
  DOMAIN_NAME: areweserveryet.org
  S3_BUCKET_NAME: areweserveryet
  S3_BUCKET_REGION: us-east-1
  FORMATION_STACK: areweserveryet-stack

jobs:
  build:
    name: Build and deploy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build site
      run: swift run
    - name: Configure AWS credentials
      id: cred
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.DEPLOYER_AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.DEPLOYER_AWS_SECRET_ACCESS_KEY }}
        aws-region: 'eu-west-2'
    - name: Deploy to AWS Cloudformation
      id: clouddeploy
      uses: aws-actions/aws-cloudformation-github-deploy@v1.0.3
      with:
        name: ${{ env.FORMATION_STACK }}
        template: stack.yaml
        no-fail-on-empty-changeset: "1"
        parameter-overrides: >-
          DomainName=${{ env.DOMAIN_NAME }},
          S3BucketName=${{ env.S3_BUCKET_NAME }},
          AcmCertificateArn=${{ secrets.CERTIFICATE_ARN }}
      if: steps.cred.outcome == 'success'
    - name: Deploy to S3
      id: s3deploy
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks --delete
      env:
        AWS_S3_BUCKET: '${{ env.S3_BUCKET_NAME }}'
        AWS_ACCESS_KEY_ID: ${{ secrets.DEPLOYER_AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.DEPLOYER_AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: '${{ env.S3_BUCKET_REGION }}'
        SOURCE_DIR: 'Output'
      if: steps.clouddeploy.outcome == 'success'
    # - name: Invalidate CloudFront
    #   uses: awact/cloudfront-action@master
    #   env:
    #     SOURCE_PATH: '/*'
    #     AWS_REGION: 'eu-west-2'
    #     AWS_ACCESS_KEY_ID: ${{ secrets.DEPLOYER_AWS_ACCESS_KEY_ID }}
    #     AWS_SECRET_ACCESS_KEY: ${{ secrets.DEPLOYER_AWS_SECRET_ACCESS_KEY }}
    #     DISTRIBUTION_ID: ${{ secrets.DISTRIBUTION_ID }}